# Generated by Django 4.2.6 on 2023-10-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_function_function1_function2_delete_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='now',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
