# Generated by Django 4.2.6 on 2023-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_post_options_remove_post_publishing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishing',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default='2023-10-29T10:15:06.149253+00:00'),
        ),
    ]
