# Generated by Django 4.2.6 on 2023-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_post_options_remove_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
