# Generated by Django 4.2.6 on 2023-10-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_post_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
