# Generated by Django 4.2.6 on 2023-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishing',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
