# Generated by Django 4.2.6 on 2023-10-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_post_publishing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publishing',
        ),
    ]
