# Generated by Django 4.2.6 on 2023-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_post_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='slug1',
            field=models.CharField(default='your_default_value_here', max_length=200),
        ),
        migrations.AddField(
            model_name='function1',
            name='slug2',
            field=models.CharField(default='your_default_value_here', max_length=200),
        ),
        migrations.AddField(
            model_name='function2',
            name='slug3',
            field=models.CharField(default='your_default_value_here', max_length=200),
        ),
    ]
